on:
  push:
    paths:
      - .github/workflows/lint-build.yml
      - dockerfile
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: dockerfile
          failure-threshold: error
      - name: docker/build
        run: >
          docker build .
          --build-arg baseimage=ubuntu:22.04
          --build-arg apt-mirror=azure.archive.ubuntu.com/ubuntu
          -t ghcr.io/kasaikou/shared-dev-container:latest
